# pack config
set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_DIRECTORY ${CMAKE_BINARY_DIR}/release)

# generated pack format
set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_STGZ "OFF")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "ON")
set(CPACK_BINARY_TZ "OFF")
set(CPACK_BINARY_TZST "OFF")
set(CPACK_BINARY_ZIP "ON")

include(CPack)
